In [1]:
import torch
import numpy as np

c:\Users\Home\AppData\Local\Programs\Python\Python39\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
print(torch.__version__)

1.13.1+cu116


In [3]:
torch.cuda.is_available()  #Is GPU available

False

In [4]:
torch.version.cuda

'11.6'

In [5]:
t = torch.tensor([1,2,3])
t

tensor([1, 2, 3])

In [8]:
# Only with GPU
# t = t.cuda()   
print(t)

tensor([1, 2, 3])


In [9]:
data = np.array([1,2,3,4])
t = torch.as_tensor(data)
t

tensor([1, 2, 3, 4], dtype=torch.int32)

In [10]:
t = torch.eye(5)
t

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [11]:
t[2][2]

tensor(1.)

In [15]:
print(t,"\n")
print(t.reshape(1,-1))

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]) 

tensor([[1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
         1., 0., 0., 0., 0., 0., 1.]])


In [17]:
t1 = torch.as_tensor(np.array([1,2,3,4]))
t2 = torch.as_tensor(np.array([10,20,30,40]))
print(t1,t2,t1+t2)

tensor([1, 2, 3, 4], dtype=torch.int32) tensor([10, 20, 30, 40], dtype=torch.int32) tensor([11, 22, 33, 44], dtype=torch.int32)


In [19]:
t = torch.eye(5,dtype=torch.int32)
t[1][0]

tensor(0, dtype=torch.int32)